Move News to a subdirectory; split by year.
seL4/website pull request #140
Opened 2021-09-12 22:55 UTC by wom-bat

As we get more and more news, having it all in one
file becomes unwieldy.  Plus, we would like to be able to have
stable URLs to news and news items.

Therefore, split news into per-year files, named 'news/2021.pml',
'news/2020.pml' and so on; and use the Python templating engine
to build indices, and to redirect from 'sel4.systems/news' to the
highest numbered news file.

Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>

2021-09-12 22:59 UTC, gernotheiser commented
This supersedes #138?

2021-09-12 23:01 UTC, wom-bat commented
> This supersedes #138?

That's the idea, yes.

2021-09-12 23:01 UTC, wom-bat commented
Changes were too substantial to put on top of the changes there, so I created a new PR.

2021-09-12 23:25 UTC, gernotheiser commented
Are the "older news" links meant to be on the most recent page only? The older ones should have at least a link back to "latest news"

2021-09-12 23:30 UTC, gernotheiser reviewed
Looks good except for back links from older pages to the latest news

2021-09-13 00:37 UTC, wom-bat commented
Added the backlinks ...

2021-09-13 00:53 UTC, gernotheiser approved these changes

2021-09-13 01:12 UTC, lsf37 approved these changes

2021-09-13 01:14 UTC, lsf37 requested changes
Had already approved, and looks good in general, but we're missing the xcalibyte news item in the 2021 list.

2021-09-13 05:23 UTC, lsf37 commented on content/news/2021.pml
> -
This is the bit that is missing

2021-09-13 05:24 UTC, lsf37 commented on content/news/2021.pml
> +	  alt="Xcalibyte logo" />
This is also a regression from a previous commit

2021-09-13 05:37 UTC, lsf37 approved these changes

2021-09-13 06:18 UTC, gernotheiser commented
URL failure is independent of this change, but I'll put in the replacement while we're at it

2021-09-13 06:28 UTC, gernotheiser commented
The NIO link is a spurious failure

2021-09-13 06:28 UTC, merged