mockup of the Services page
seL4/website pull request #30
Opened 2020-10-08 04:19 UTC by june-andronick

Signed-off-by: Gerwin Klein <gerwin.klein@data61.csiro.au>

2020-11-04 07:30 UTC, june-andronick commented
I think I'm done with this final draft. To note:
- Cog and DW have a separate page on the Foundation website
- Breakaway doesn't (but we haven't ask Benno yet; just took blurb from announcement)

Next step would be to write to the 3 of them with screenshots and ask for feedback. Given I'm away next week, sooner is better ;)

2020-11-04 07:30 UTC, june-andronick commented
Also: I haven't added AOS yet

2020-11-04 07:33 UTC, gernotheiser commented
I get a 404 on the preview link

2020-11-04 07:39 UTC, lsf37 commented
Preview link [here](https://htmlpreview.github.io/?https://github.com/seL4/website_pr_hosting/blob/PR_30/localhost/index.html)

2020-11-04 07:46 UTC, gernotheiser commented
Services page looks good (but I'd like AOS added before we go live ;-)
Also, the bullet list should link to the relevant sections.

The individual companies' pages they will probably want to change, now that the formatting is defined, they don't look so great. I suggest sending them not just a screen shot but the actual HTML source so they can play with it themselves.

2020-11-05 08:56 UTC, lsf37 approved these changes
Happy with the current state, pending approval by the members.

2020-11-05 14:39 UTC, Furao requested changes
Just a couple of text issues. I appreciate the endorsement process page. That will be helpful.

2020-11-05 14:39 UTC, Furao commented on content/Foundation/Services/dornerworks.pml
> +         realitywith FPGA, hardware, and embedded software engineering
add a space between reality and with

2020-11-05 14:39 UTC, Furao commented on content/Foundation/Services/dornerworks.pml
> +</li>
Should be:

```
<li>
  Guest OS and hardware porting
</li>
<li>
  Virtualization and hypervisor distributions
</li>

2020-11-05 22:08 UTC, lsf37 commented on content/Foundation/Services/dornerworks.pml
> +         realitywith FPGA, hardware, and embedded software engineering
Thanks for spotting these, now fixed!

2020-11-05 22:08 UTC, lsf37 commented on content/Foundation/Services/dornerworks.pml
> +</li>
Done!

2020-11-06 08:46 UTC, lsf37 commented
(reverted accidental push)

2020-11-16 03:49 UTC, june-andronick commented
I've added AOS as an endorsed training.
I've deleted commented out sections.
I changed the order and names in the drop-down menus. 
Cog and Breakaway have accepted the text for their parts.
This is ready for review and merge.

2020-11-16 06:13 UTC, gernotheiser approved these changes

2020-11-16 06:41 UTC, merged